# ***************************************************************
# start local development environment (without application)
# ***************************************************************
name: aam-services
services:
  maildev:
    image: maildev/maildev
    ports:
      - "1025:1025"
      - "1080:1080"

  db-couch:
    image: couchdb:3.3
    volumes:
      - ~/docker-volumes/aam-digital/aam-services/db-couch/document-data:/opt/couchdb/data
      - ~/docker-volumes/aam-digital/aam-services/db-couch/document-etc-locald:/opt/couchdb/etc/local.d
      - ~/docker-volumes/aam-digital/aam-services/db-couch/document-log:/opt/couchdb/log
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: docker
      COUCHDB_SECRET: docker
    ports:
      - "5984:5984"

  db-keycloak:
    image: postgres:16
    volumes:
      - ~/docker-volumes/aam-digital/aam-services/db-keycloak/postgresql-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: keycloak
    ports:
      - "5401:5432"

  db-backend:
    image: postgres:16.5-bookworm
    volumes:
      - ~/docker-volumes/aam-digital/aam-services/db-backend/postgresql-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: aam-backend-service
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: docker
    ports:
      - "5402:5432"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    volumes:
      - ~/docker-volumes/aam-digital/aam-services/rabbitmq/data:/var/lib/rabbitmq/
      - ~/docker-volumes/aam-digital/aam-services/rabbitmq/log:/var/log/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  sqs:
    image: ghcr.io/aam-digital/aam-sqs-mac:latest
    platform: linux/amd64
    depends_on:
      - db-couch
    ports:
      - "4984:4984"
    volumes:
      - ~/docker-volumes/aam-digital/aam-services/sqs/data:/data
    environment:
      SQS_COUCHDB_URL: http://db-couch:5984

  keycloak:
    image: quay.io/keycloak/keycloak:23.0
    volumes:
      - ~/docker-volumes/aam-digital/aam-services/keycloak/data:/opt/keycloak/data
      - ~/docker-volumes/aam-digital/aam-services/keycloak/themes:/opt/keycloak/themes
    ports:
      - "8080:8080"
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://db-keycloak:5432/postgres
      KC_DB_SCHEMA: public
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: docker
    depends_on:
      - db-keycloak
    command:
      - start-dev

  carbone-io:
    image: carbone/carbone-ee
    platform: linux/amd64
    volumes:
      - ~/docker-volumes/aam-digital/aam-services/carbone-io/template:/app/template
      - ~/docker-volumes/aam-digital/aam-services/carbone-io/render:/app/render
    ports:
      - "4000:4000"

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686" # the jaeger UI
      - "4317:4317" # the OpenTelemetry collector grpc
      - "4318:4318" # the OpenTelemetry collector http
    environment:
      - COLLECTOR_OTLP_ENABLED=true
