name: aam-digital-developer-stack
services:
  # ***************************************************************
  # dev tools
  # ***************************************************************
  reverse-proxy:
    image: caddy:2.9-alpine
    networks:
      - aam-digital
    extra_hosts:
      - "host.docker.internal:host-gateway" # (linux only) support for accessing processes on host machine
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./container-data/caddy-authorities:/data/caddy/pki/authorities/local
    ports:
      - "80:80" # http
      - "443:443" # https
      - "2019:2019" # caddy api

  maildev:
    image: maildev/maildev:2.2.1
    networks:
      - aam-digital

  # ***************************************************************
  # couchdb
  # ***************************************************************

  db-couch:
    image: couchdb:3.4.2
    networks:
      - aam-digital
    volumes:
      - ./container-data/db-couch/data:/opt/couchdb/data
      - ./container-data/db-couch/local.d:/opt/couchdb/etc/local.d
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: docker

  # ***************************************************************
  # keycloak
  # ***************************************************************

  keycloak_26:
    image: quay.io/keycloak/keycloak:26.0.7-0
    container_name: keycloak
    depends_on:
      - db-keycloak
    ports:
      - "8080:8080"
    networks:
      - aam-digital
    command: "start --proxy-headers forwarded"
    environment:
      KC_HTTP_ENABLED: true
      KC_HOSTNAME: https://keycloak.localhost
      KC_FRONTEND_URL: https://keycloak.localhost
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://db-keycloak:5432/postgres
      KC_DB_SCHEMA: public
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: docker
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: docker
      JAVA_TOOL_OPTIONS: ${JAVA_TOOL_OPTIONS:-} # (macOS only) bug on M4 chips with Sequoia 15.2: https://github.com/corretto/corretto-21/issues/85
    volumes:
      - ./container-data/keycloak/providers:/opt/keycloak/providers
    # - ./container-data/keycloak/themes:/opt/keycloak/themes
    profiles:
      - keycloak_latest

  db-keycloak:
    image: postgres:16
    networks:
      - aam-digital
    volumes:
      - ./container-data/db-keycloak/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: docker
    ports:
      - "5401:5432"

# Currently Keycloak 23 is used in production:
  keycloak_23:
    image: quay.io/keycloak/keycloak:23.0.7
    # our actual production image (currently not available publicly, however): ghcr.io/aam-digital/aam-keycloak:23.0.7
    container_name: keycloak
    networks:
      - aam-digital
    ports:
      - "8080:8080"
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://db-keycloak_23:5432/postgres
      KC_DB_SCHEMA: public
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: docker
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: docker
      KC_HOSTNAME: keycloak.localhost
      KC_PROXY: edge
    depends_on:
      - db-keycloak_23
    command: start-dev
    # for production settings use command: start --optimized --spi-theme-login-theme=aam-theme
    volumes:
      - ./container-data/keycloak/providers:/opt/keycloak/providers
    #  - ./container-data/keycloak/themes:/opt/keycloak/themes

  db-keycloak_23:
    image: postgres:16
    volumes:
      - ./container-data/db-keycloak23/postgresql-data:/var/lib/postgresql/data
    networks:
      - aam-digital
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: docker

  # ***************************************************************
  # rabbitmq
  # ***************************************************************

  rabbitmq:
    image: rabbitmq:3-management-alpine
    hostname: rabbitmq
    networks:
      - aam-digital
    volumes:
      - ./container-data/rabbitmq/data:/var/lib/rabbitmq/
    ports:
      - "5672:5672"
      - "15672:15672"

  # ***************************************************************
  # replication-backend
  # ***************************************************************

  replication-backend:
    image: ghcr.io/aam-digital/replication-backend:latest
    depends_on:
      - db-couch
    networks:
      - aam-digital
    environment:
      DATABASE_URL: http://db-couch:5984
      DATABASE_NAME: app
      DATABASE_USER: admin
      DATABASE_PASSWORD: docker
      JWT_SECRET: someJwtSecret
      JWT_PUBLIC_KEY: "-----BEGIN PUBLIC KEY-----\n${REPLICATION_BACKEND_PUBLIC_KEY:?REPLICATION_BACKEND_PUBLIC_KEY is not set}\n-----END PUBLIC KEY-----"
      SENTRY_DSN: ""
      SENTRY_ENABLED: false
      SENTRY_INSTANCE_NAME: ""
      SENTRY_ENVIRONMENT: ""
      PORT: 5984

  # ***************************************************************
  # aam-backend-service
  # ***************************************************************

  aam-backend-service:
    image: ghcr.io/aam-digital/aam-backend-service:${AAM_BACKEND_SERVICE_VERSION:-latest}
    networks:
      - aam-digital
    external_links:
      - reverse-proxy:aam.localhost
    depends_on:
      - aam-backend-service-db
      - rabbitmq
    env_file:
      - .env
    environment:
      JAVA_TOOL_OPTIONS: ${JAVA_TOOL_OPTIONS:-} # (macOS only) bug on M4 chips with Sequoia 15.2: https://github.com/corretto/corretto-21/issues/85

  aam-backend-service-db:
    image: postgres:16.6-bookworm
    networks:
      - aam-digital
    environment:
      POSTGRES_DB: aam-backend-service
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: docker
    ports:
      - "5402:5432"

  # ***************************************************************
  # aam-backend-service feature dependencies (todo: os specific platform and images)
  # ***************************************************************

  sqs:
    image: ghcr.io/aam-digital/aam-sqs-linux:latest
    platform: linux/amd64
    networks:
      - aam-digital
    depends_on:
      - db-couch
    ports:
      - "4984:4984"
    volumes:
      - ./container-data/sqs/data:/data
    environment:
      SQS_COUCHDB_URL: http://db-couch:5984
    profiles:
      - include-private

  carbone-io:
    image: carbone/carbone-ee
    platform: linux/amd64
    networks:
      - aam-digital
    volumes:
      - ./container-data/carbone-io/template:/app/template
      - ./container-data/carbone-io/render:/app/render
    ports:
      - "4000:4000"

  # ***************************************************************
  # tracing and monitoring (todo)
  # ***************************************************************

  #  jaeger:
  #    image: jaegertracing/all-in-one:latest
  #    ports:
  #      - "16686:16686" # the jaeger UI
  #      - "4317:4317" # the OpenTelemetry collector grpc
  #      - "4318:4318" # the OpenTelemetry collector http
  #    environment:
  #      - COLLECTOR_OTLP_ENABLED=true

networks:
  aam-digital:
    external: true