openapi: 3.0.3
info:
  title: Notification API
  description: Provide (push) notification functionality to users and devices.
  version: 1.0.0
servers:
  - url: /v1/notification

paths:
  /device:
    post:
      summary: Register a new device to receive notifications.
      tags:
        - device
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeviceRegistration'
      responses:
        204:
          description: Device registration successful
        400:
          description: Bad request (e.g. the device is already registered, or no subject in the token)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        401:
          description: No valid access token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /device/{deviceId}:
    get:
      summary: Check if the device is correctly registered for push notifications
      parameters:
        - in: path
          name: deviceId
          schema:
            type: string
          required: true
      tags:
        - device
      responses:
        403:
          description: Device does not belong to user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        404:
          description: Device registration does not exist
        200:
          description: Device registration exists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeviceRegistrationCheckResponse'
    delete:
      summary: Delete an existing device registration.
      parameters:
        - in: path
          name: deviceId
          schema:
            type: string
          required: true
      tags:
        - device
      responses:
        403:
          description: Device does not belong to user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        404:
          description: Device registration does not exist
        204:
          description: Device registration was removed

  /message/device-test:
    post:
      summary: Send a hello-world notification to all registered devices of the current user
      tags:
        - message
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TestMessageResponse'

components:
  schemas:
    DeviceRegistration:
      type: object
      required:
        - deviceToken
      properties:
        deviceName:
          type: string
        deviceToken:
          type: string

    TestMessageResponse:
      type: object
      properties:
        receiverIds:
          type: array
          items:
            type: string
    
    DeviceRegistrationCheckResponse:
      type: object
      properties:
        deviceToken:
          type: string
        deviceName:
          type: string

    Error:
      type: object
      properties:
        errorCode:
          type: string
        errorMessage:
          type: string
