openapi: 3.0.3
info:
  title: Skill API
  description: REST API for handling skill and user profile mapping.
  version: 1.0.0
servers:
  - url: /v1/skill

paths:
  /user-profile:
    get:
      summary: Return all UserProfile
      description: todo
      tags:
        - skills
      parameters:
        - name: fullName
          in: query
          required: false
          schema:
            type: string
            description: Optional fullName filter
        - name: email
          in: query
          required: false
          schema:
            type: string
            description: Optional email filter
        - name: phone
          in: query
          required: false
          schema:
            type: string
            description: Optional phone filter
        - name: pageSize
          in: query
          required: false
          schema:
            type: number
            minimum: 1
            maximum: 100
            default: 1
            required: false
            description: Number of elements returned by each page
        - name: page
          in: query
          required: false
          schema:
            type: number
            minimum: 1
            default: 1
            required: false
            description: The page to return
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserProfilePage'

  /user-profile/{userProfileId}:
    get:
      summary: Return all UserProfile
      description: todo
      tags:
        - skills
      parameters:
        - name: userProfileId
          in: path
          required: true
          schema:
            type: string
            format: UUID
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'

  /sync:
    get:
      summary: Return sync status for projects
      description: Returns a list of all configured projects and the latest sync attempt
      tags:
        - admin
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Sync'

  /sync/{projectId}:
    post:
      summary: Trigger project sync
      description: Import all changes for this project from SkillProvider. You can choose to sync just the changes from an specific date (DELTA) or do a full import (FULL).
      tags:
        - admin
      parameters:
        - name: syncMode
          in: query
          required: false
          schema:
            type: string
            default: DELTA
            enum:
              - DELTA
              - FULL
        - name: updatedFrom
          description: Define the start date for the Delta load. Just used in syncMode DELTA, uses latest sync date if not defined manually.
          in: query
          required: false
          schema:
            type: string
            default: "2024-12-03T11:50:00.231Z"
            format: date-time
        - name: projectId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Sync process started, can take some minutes until all changes are imported.

components:
  schemas:
    Pagination:
      type: object
      properties:
        currentPage:
          type: number
          minimum: 1
          default: 1
        pageSize:
          type: number
          minimum: 1
          maximum: 100
          default: 10
        totalPages:
          type: number
          example: 5
        totalElements:
          type: number
          example: 42

    UserProfilePage:
      type: object
      properties:
        pagination:
          $ref: '#/components/schemas/Pagination'
        results:
          type: array
          items:
            $ref: '#/components/schemas/UserProfile'

    UserProfile:
      type: object
      properties:
        id:
          type: string
          format: uuid
        fullName:
          type: string
        phone:
          type: string
        email:
          type: string
        skills:
          type: array
          items:
            $ref: '#/components/schemas/Skill'
        updatedAtExternalSystem:
          type: string
          format: date-time
        importedAt:
          type: string
          format: date-time
        latestSyncAt:
          type: string
          format: date-time

    Sync:
      type: object
      properties:
        project:
          type: string
        latestSync:
          type: string
          format: date-time

    Skill:
      type: object
      properties:
        escoUri:
          type: string
        usage:
          type: string
          enum:
            - ALMOST_NEVER
            - SOMETIMES
            - OFTEN
            - ALMOST_ALWAYS
            - ALWAYS
