spring:
  application:
    name: aam-backend-service
  main:
    banner-mode: off
  jackson:
    deserialization:
      accept-empty-string-as-null-object: true
  rabbitmq:
    listener:
      simple:
        prefetch: 1
  datasource:
    driver-class-name: org.h2.Driver
    username: local
    password: local
    url: jdbc:h2:file:./data/dbh2;DB_CLOSE_DELAY=-1
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
  threads:
    virtual:
      enabled: true

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include:
          - info
          - health
  tracing:
    sampling:
      probability: 1

# enable/disables event processing for each queue
events:
  listener:
    report-calculation:
      enabled: true

---

spring:
  config:
    activate:
      on-profile: local-development
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/dummy-realm
  rabbitmq:
    virtual-host: local
    listener:
      direct:
        retry:
          enabled: true
          max-attempts: 5
      simple:
        observation-enabled: true
    username: local-spring
    password: docker


server:
  error:
    include-message: always
    include-binding-errors: always
  port: 9000
  servlet:
    context-path: /api

logging:
  level:
    #    org.springframework.amqp.rabbit: warn
    #    org.springframework.web: debug
    #    org.springframework.http: debug
    com.aamdigital.aambackendservice: trace

aam-render-api-client-configuration:
  base-path: https://pdf.aam-digital.dev
#  auth-config:
#   client-id: <needs-environment-configuration>
#   client-secret: <needs-environment-configuration>
#   token-endpoint: <needs-environment-configuration>
#   grant-type: <needs-environment-configuration>
#   scope: <needs-environment-configuration>

couch-db-client-configuration:
  base-path: http://localhost:5984
  basic-auth-username: admin
  basic-auth-password: docker

sqs-client-configuration:
  base-path: http://localhost:4984
  basic-auth-username: admin
  basic-auth-password: docker

events:
  listener:
    report-calculation:
      enabled: true

database-change-detection:
  enabled: true

sentry:
  logging:
    enabled: false

management:
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces
