name: aam-backend-service-analyse

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/aam-backend-service-analyse.yml'
      - 'application/aam-backend-service/**'
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]

jobs:
  test_coverage:
    name: Run tests and coverage calculation
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: application/aam-backend-service
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 17
          cache: 'gradle'

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Tests and generate Jacoco Test Report
        env:
          JACOCO_SOURCE_PATH: application/aam-backend-service/src/main/kotlin
        run: |
          export DOCKER_AUTH_CONFIG=$(cat $HOME/.docker/config.json)
          export TESTCONTAINERS_RYUK_DISABLED=true
          echo TESTCONTAINERS_RYUK_DISABLED
          ./gradlew jacocoTestReport --no-daemon

      - name: Publish code coverage to code climate
        uses: paambaati/codeclimate-action@v5.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
          JACOCO_SOURCE_PATH: application/aam-backend-service/src/main/kotlin
        with:
          coverageLocations: application/aam-backend-service/build/reports/jacoco/test/jacocoTestReport.xml:jacoco

      - name: Add code coverage to PR
        uses: madrapps/jacoco-report@v1.6.1
        with:
          paths: application/aam-backend-service/build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 80
          min-coverage-changed-files: 80
          title: Code Coverage Analyse
          update-comment: true
